// Copyright 2021 @choko-wallet/account-abstraction authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @choko-wallet/dev, do not edit

export const packageInfo = { name: '@choko-wallet/account-abstraction', version: '0.1.10-21' };
