// Copyright 2021-2022 @choko-wallet/abi authors & contributors
// SPDX-License-Identifier: Apache-2.0

const fs = require('fs');
const path = require('path');

const outputFile = path.join(__dirname, 'abi.ts');
const abiFiles = path.join(__dirname, 'abi');

const iterateAbis = () => {
  const abis = [];

  const files = fs.readdirSync(abiFiles);

  for (const file of files) {
    const a = require(
      path.join(abiFiles, file)
    );

    abis.push({
      content: JSON.stringify(a),
      name: file.split('.')[0]
    });
  }

  return abis;
};

const main = () => {
  const abis = iterateAbis();
  const w = fs.createWriteStream(outputFile, { flags: 'w' });

  w.write(
    `// Copyright 2021-2022 @choko-wallet/abi authors & contributors
// SPDX-License-Identifier: Apache-2.0

// this file is auto generated by "yarn build:abi"

/* eslint-disable */
const abis: {[key: string]: string} = {
`);

  for (const abi of abis) {
    w.write(` '${abi.name}': '${abi.content}',`);
  }

  w.write(`
}
export { abis };
`);
};

main();
