// Copyright 2021 @choko-wallet/abi authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @choko-wallet/dev, do not edit

export const packageInfo = { name: '@choko-wallet/abi', version: '0.1.8-7' };
