// Copyright 2021-2022 @choko-wallet/abi authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @choko-wallet/dev, do not edit

export const packageInfo = { name: '@choko-wallet/sdk', version: '0.1.6-9' };
