// Copyright 2021 @choko-wallet/assets authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @choko-wallet/dev, do not edit

export const packageInfo = { name: '@choko-wallet/assets', version: '0.1.8-6' };
