// Copyright 2021 @choko-wallet/token-price authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @choko-wallet/dev, do not edit

export const packageInfo = { name: '@choko-wallet/token-price', version: '0.1.10-21' };
